---
title: "02-modelling"
format: html
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(cmdstanr)
library(brms)
library(posterior)
library(coretta2018itapol)
library(coretta2019eng)
library(ggdist)

```

```{r}
#| label: data

data("token_measures")
data("eng_durations")

itapol <- token_measures |> 
  dplyr::select(speaker, v1_duration, voicing = c2_phonation, language, speech_rate) |> 
  mutate(
    num_syl = "di",
    rate = (speech_rate - mean(speech_rate, na.rm = TRUE)) / sd(speech_rate, na.rm = TRUE)
  )

eng <- eng_durations |> 
  dplyr::select(speaker, v1_duration, voicing, num_syl, speech_rate) |> 
  mutate(
    language = "English",
    rate = (speech_rate - mean(speech_rate, na.rm = TRUE)) / sd(speech_rate, na.rm = TRUE)
  )

ipe <- bind_rows(itapol, eng) |> 
  drop_na(v1_duration)
```

```{r}
#| label: ipe-dat

ipe_dat <- list(
  N = nrow(ipe),
  P = length(unique(ipe$speaker)),
  L = 3,
  y = log(ipe$v1_duration),
  # voiceless = 0, voiced = 1
  voicing = as.numeric(factor(ipe$voicing, levels = c("voiceless", "voiced"))) - 1,
  rate = ipe$rate,
  # di = 0 and mono = 1
  syllables = as.numeric(as.numeric(factor(ipe$num_syl, levels = c("mono", "di"))) == 1),
  participant = as.numeric(as.factor(ipe$speaker)),
  language = as.numeric(as.factor(ipe$language))
)
```

```{r}
#| label: bm-1-mod
bm_1_mod <- cmdstan_model("scripts/bm-1.stan")
```

```{r}
#| label: bm-1-fit
bm_1_fit <- bm_1_mod$sample(
  data = ipe_dat,
  seed = 2183,
  chains = 4, parallel_chains = 4,
  # ~1-2% divergent transitions, increase adapt delta
  adapt_delta = 0.99,
  # 7 transitions hit max treedepth, increase
  max_treedepth = 15
)
```

```{r}
#| label: bm-1-summary

bm_1_summary <- bm_1_fit$summary(variables = c("intercept", "b_voicing", "b_syllables_en", "b_voicing_syllables_en", "b_rate")) |> 
  mutate(
    across(where(is.numeric), ~round(.x, 2))
  )
```

```{r}
#| label: bm-1-draws

bm_1_draws <- bm_1_fit$draws(
  c("intercept", "b_voicing", "b_syllables_en", "b_voicing_syllables_en", "b_rate", "r_participant", "corr_participant")
) |> as_draws_df()

```

```{r}
#| label: voi-draws
voi_draws <- bm_1_draws |> 
  select(en_di = `b_voicing[1]`, it_di = `b_voicing[2]`, po_di = `b_voicing[3]`, b_voicing_syllables_en) |> 
  mutate(
    en_mono = en_di + b_voicing_syllables_en
  ) |> 
  select(-b_voicing_syllables_en) |> 
  pivot_longer(everything())
```

```{r}
#| label: fig-voi-draws
voi_draws |> 
  ggplot(aes(100 * exp(value) - 100, name)) +
  geom_vline(xintercept = 0) +
  stat_halfeye()
```
